name: Akeyless Version Update
on:
  push:
    branches:
      - main

jobs:
  version-check-job:
    runs-on: ubuntu-latest
    name: Job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Execute Script
	run: bash ./akey_version_update.sh 
