name: Akeyless Version Update
on:
  push:
    branches:
      - main

jobs:
  version-check-job:
    runs-on: ubuntu-latest
    name: Job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Execute Script
        run: bash ./akey_version_update.sh
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }} 
